Documentation about custom camera calibrations
annotell/public-docs pull request #33
Opened 2023-10-30 13:20 UTC by olinoskar

2023-10-30 13:21 UTC, olinoskar commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +A [Rust file](https://github.com/annotell/kognic-io-python/blob/1aa5a12496296ec943d68ec94eefab42158fedac/examples/calibration/custom/pinhole.rs)
Change urls here when the PR in kognic-io is merged

2023-10-31 12:38 UTC, kallus requested changes
Well written!

2023-10-31 12:38 UTC, kallus commented on docs-src/sidebars.js
> +        "kognic-io/calibrations/cameras-custom",
Standard should maybe come before custom here. I think it would make sense if the standard was above custom in the menu.

2023-10-31 12:38 UTC, kallus commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +to validate the calibration when during creation. It is recommended to provide a few test cases to make sure that the
```suggestion
to validate the calibration during creation. It is recommended to provide a few test cases to make sure that the
```

2023-10-31 12:38 UTC, kallus commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +| Key                   | Value                         | Parameters         |
Move this table to come directly after "The table below
show the attributes of the `CustomCameraCalibration` object."

2023-10-31 12:38 UTC, kallus commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +function must take three arguments of type `float64` and return two values of type `float64`. So the text representation
```suggestion
function must take three arguments of type `float64` and return two values of type `float64`. Thus, the WebAssembly text representation of
```

2023-10-31 12:38 UTC, kallus commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +This requires `wasmtime` to be installed which is an optional dependency kognic-io. Run `pip install kognic-io[wasm]` to
```suggestion
This requires `wasmtime` to be installed which is an optional of dependency kognic-io. Run `pip install kognic-io[wasm]` to
```

2023-10-31 12:38 UTC, kallus commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +We provide validation code both as python functions and via the `kognicutil` cli. We validate things such as but limited to
```suggestion
We provide validation code both as python functions and via the `kognicutil` cli. We validate things such as but not limited to
```

2023-10-31 12:38 UTC, kallus commented on docs-src/docs/kognic-io/calibrations/cameras-custom.md
> +| **Language** | **Target**  | **Compilation tool** |
Put the table directly after "languages, see table below."

2023-10-31 12:48 UTC, kallus approved these changes
:star:

2023-10-31 15:39 UTC, merged